pbhms/billing/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'billing'
urlpatterns = [
    path('', views.billing, name = 'home'),
]

pbhms/guests/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'guests'
urlpatterns = [
    path('', views.guests, name = 'home'),
    path('checkin/', views.checkin, name = 'checkin'),
    path('checkout/', views.checkout, name = 'checkout'),
]

pbhms/pbhms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('billing/', include('billing.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('guests/', include('guests.urls')),
    path('rooms/', include('rooms.urls')),
    path('services/', include('services.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pbhms/billing/models.py
from django.db import models
from django.utils import timezone
from decimal import Decimal
from guests.models import CheckIn, CheckOut

class Billing(models.Model):
    check_out = models.OneToOneField(CheckOut, on_delete=models.CASCADE, related_name='bill', null=True, blank=True)
    check_in = models.ForeignKey(CheckIn, on_delete=models.CASCADE, related_name='bills')

    room_bill = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    room_service = models.DecimalField(max_digits=10, decimal_places=2)
    food = models.DecimalField(max_digits=10, decimal_places=2)
    bottles = models.DecimalField(max_digits=10, decimal_places=2)
    in_room_facilities = models.DecimalField(max_digits=10, decimal_places=2)
    miscellaneous = models.DecimalField(max_digits=10, decimal_places=2)

    total = models.DecimalField(max_digits=12, decimal_places=2, default=0, editable=False)
    date = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        # Validate first
        if not self.check_out:
            raise ValueError("Cannot create a bill without a checkout record.")
        if self.check_out.check_in != self.check_in:
            raise ValueError("Check In and Check Out must belong to the same guest.")

        # Room rates
        room_rates = {
            'ER': 5000,
            'DR': 2500,
            'NR-(AC)': 1500,
            'NR-(WAC)': 1000,
        }

        # Compute room bill
        room_rate = room_rates.get(self.check_in.room_type, 0)
        self.room_bill = Decimal(room_rate) * Decimal(self.check_out.no_of_days)

        # Compute total
        self.total = (
            self.room_service +
            self.food +
            self.bottles +
            self.in_room_facilities +
            self.miscellaneous +
            self.room_bill
        )

        super().save(*args, **kwargs)

    def __str__(self):
        return  f"Rs.{self.total}"

pbhms/billing/forms.py
from django import forms
from django.utils import timezone
from .models import Billing

class billing_form(forms.ModelForm):
    class Meta:
        model = Billing
        fields = "__all__"
        widgets = {
            'check_in': forms.Select(attrs={'class': 'bg-black w-full focus:outline-none'}),
            'check_out': forms.Select(attrs={'class': 'bg-black w-full focus:outline-none'}),
            'room_service': forms.TextInput(attrs={'placeholder': 'Enter total bill of Room service if taken', 'class': 'w-full focus:outline-none'}),
            'food': forms.TextInput(attrs={'placeholder': 'Enter total food bill if ordered', 'class': 'w-full focus:outline-none'}),
            'room_bill': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'w-full focus:outline-none'}),
            'bottles': forms.TextInput(attrs={'placeholder': 'Enter the water bill if taken', 'class': 'w-full focus:outline-none'}),
            'in_room_facilities': forms.TextInput(attrs={'placeholder': 'Enter the bill for room facilities', 'class': 'w-full focus:outline-none'}),
            'total': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'w-full focus:outline-none'}),
            'miscellaneous': forms.TextInput(attrs={'placeholder': 'Enter any miscellaneous bill', 'class': 'w-full focus:outline-none'}),
            'date': forms.DateTimeInput(attrs={'value': timezone.now().strftime('%Y-%m-%d %H:%M:%S'), 'class': 'focus:outline-none' ,'readonly': 'readonly', 'class': 'w-full'})
        }

pbhms/billing/views.py
from django.shortcuts import render
from .forms import billing_form
from guests.models import CheckOut

# Create your views here.
def billing(request):
    guest = None
    aadhaar_search = request.GET.get("aadhaar_search")
    if aadhaar_search:
        try:
            guest = CheckOut.objects.get(check_in__aadhaar_card = aadhaar_search)
        except CheckOut.DoesNotExist:
            guest = None
    if request.method == "POST":
        form = billing_form(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = billing_form()
    return render(request, 'billing.html', {'form': form, 'guest': guest})

pbhms/billing/templates/billing.html
{% extends "website/index.html" %} {% block title %}Billing and Payments{% endblock title %}
{% block content %}
<section style = "margin-top:100px">
  <div class="w-full h-full flex items-center justify-center flex-col gap-10">
    <div class="text-5xl font-bold">Create Bills for a Guest stay</div>
    <div class="w-[95%] flex flex-row justify-center gap-4">
      <div class="w-full flex flex-col gap-4">
        <div class="text-2xl font-bold">
            Calculate total bill for a guest:
        </div>
        <div class="form-div w-full">
          {% if form.errors %}
          <div class="text-red-500 mb-4">{{ form.errors }}</div>
          {% endif %}

          <form method="POST" action="{% url 'billing:home' %}">
            {% csrf_token %}

            <div class="flex flex-col border border-white p-4 rounded-2xl">
              <div class="">
                <label for="{{form.check_in.id_for_label}}">Select Guest from Check-In:</label>
                {{form.check_in}}
                {{form.check_in.errors}}
              </div>
              <div class="">
                <label for="{{form.check_out.id_for_label}}">Select Guest from Check-Out:</label>
                {{form.check_out}}
                {{form.check_out.errors}}
              </div>
              <div class="">
                <label for="{{form.room_service.id_for_label}}">Room service (if taken):</label>
                {{form.room_service}}
                {{form.room_service.errors}}
              </div>
              <div class="">
                <label for="{{form.food.id_for_label}}">Food Bill (if ordered):</label>
                {{form.food}}
                {{form.food.errors}}
              </div>
              <div class="">
                <label for="{{form.bottles.id_for_label}}">Water Bottles (if taken):</label>
                {{form.bottles}}
                {{form.bottles.errors}}
              </div>
              <div class="">
                <label for="{{form.in_room_facilities.id_for_label}}">In Room Facilities (if taken):</label>
                {{form.in_room_facilities}}
                {{form.in_room_facilities.errors}}
              </div>
              <div class="">
                <label for="{{form.miscellaneous.id_for_label}}">Miscellaneous Bill:</label>
                {{form.miscellaneous}}
                {{form.miscellaneous.errors}}
              </div>
              {% comment %} <div class="">
                <label for="{{form.room_bill.id_for_label}}">Room Bill:</label>
                {{form.room_bill}}
                {{form.room_bill.errors}}
              </div> {% endcomment %}
              <div class="">
                <label for="{{form.date.id_for_label}}">Date and Time:</label>
                {{form.date}}
                {{form.date.errors}}
              </div>
              {% comment %} <div class="">
                <label for="{{form.total.id_for_label}}">Total:</label>
                {{form.total}}
                {{form.total.errors}}
              </div> {% endcomment %}
            </div>

            <button
              type="submit"
              class="cursor-pointer p-1 w-full bg-white hover:bg-gray-100 duration-300 font-medium text-black rounded-xl mt-4"
            >
              Submit
            </button>
          </form>
        </div>
      </div>
      <div class="w-full flex flex-col gap-4">
        <div class="text-2xl font-bold">
          Fetch Bill details of a Guest:
        </div>
        <div class="form-div w-full">
          {% if form.errors %}
          <div class="text-red-500 mb-4">{{ form.errors }}</div>
          {% endif %}
          <form method="GET" action="{% url 'billing:home' %}" class="w-full">
            <div class="flex flex-col border border-white p-4 rounded-2xl">
              <label class="text-white font-medium">Aadhaar Card:</label>

              <input
                type="text"
                name="aadhaar_search"
                placeholder="Enter Aadhaar Number"
                class="text-white p-2 rounded"
              />

              {% if guest %}
              <div class="text-white mt-4">
                <h2 class="font-bold text-lg">Guest Details</h2>
                <p><strong>Name:</strong> {{ guest.check_in }}</p>
                <p><strong>Aadhaar Card:</strong>{{guest.check_in.aadhaar_card}}</p>
                <p><strong>No. of Day(s):</strong> {{ guest.no_of_days }}</p>
                <p><strong>Date of checkin:</strong> {{ guest.check_in.date }}</p>
                <p><strong>Date of checkout:</strong> {{ guest.checkout_date }}</p>
                <p><strong>Mobile:</strong> {{ guest.check_in.mobile }}</p>
                <p><strong>Alloted Room:</strong> {{ guest.check_in.alloted_room }}</p>
                <p><strong>Bill:</strong> {{ guest.bill }}</p>
              </div>
              {% endif %}
            </div>

            <div class="flex flex-row gap-1">
              <button
              type="submit"
              class="cursor-pointer p-1 w-1/2 bg-white hover:bg-gray-100 duration-300 font-medium text-black rounded-xl mt-4"
            >
              Search
            </button>
            <button type="submit" class="cursor-pointer p-1 w-1/2 bg-white hover:bg-gray-100 duration-300 font-medium text-black rounded-xl mt-4 {% if not guest %} opacity-50 cursor-not-allowed {% endif %}" onclick = window.location.href = "{% url 'guests:checkout' %}" {% if not guest %} disabled {% endif %}>
              Clear
            </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}