pbhms/billing/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'billing'
urlpatterns = [
    path('', views.billing, name = 'home'),
]

pbhms/dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.dashboard, name = 'home'),
]

pbhms/guests/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'guests'
urlpatterns = [
    path('', views.guests, name = 'home'),
    path('checkin/', views.checkin, name = 'checkin'),
    path('checkout/', views.checkout, name = 'checkout'),
]

pbhms/pbhms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('billing/', include('billing.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('guests/', include('guests.urls')),
    path('rooms/', include('rooms.urls')),
    path('services/', include('services.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pbhms/rooms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'rooms'

urlpatterns = [
    path('', views.rooms, name = 'home'),
]

pbhms/services/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'services'
urlpatterns = [
    path('', views.services, name = 'home'),
]

pbhms/dashboard/models.py
from django.db import models

# Create your models here.

pbhms/dashboard/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'dashboard.html')

pbhms/dashboard/templates/dashboard.html
{% extends "website/index.html" %} {% block title %}Dashboard{% endblock title%}
{% block content %}
<section class="h-full">
  <div class="flex justify-center items-center h-full flex-col gap-5">
    <div class="some-heading h-[40%] w-full flex items-center justify-center text-6xl">Dashboard</div>
    <div class="main-content flex flex-row w-full h-[50%] justify-center">
      <div class="flex lg:flex-row w-[95%] justify-evenly gap-2.5 sm:flex-col">
        <div class="first-card w-1/4 flex flex-col border rounded-3xl border-gray-600 gap-2.5 p-5">
          <a href="{% url 'billing:home' %}"><div class="card-head flex justify-center h-15 items-center border-white border-2 rounded-3xl bg-white text-black hover:bg-gray-200 duration-300 font-medium">Billings and Payments</div></a>
          <div class="card-content flex items-center h-full text-gray-500">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Placeat aut molestiae itaque ducimus eos amet quas vero perferendis praesentium, saepe doloribus maiores, repellendus soluta? Nulla qui quibusdam porro, nihil aut modi architecto?</div>
        </div>
        <div class="second-card w-1/4 flex flex-col border rounded-3xl border-gray-600 gap-2.5 p-5">
          <a href="{% url 'guests:home' %}"><div class="card-head flex justify-center h-15 items-center border-white border-2 rounded-3xl bg-white text-black hover:bg-gray-200 duration-300 font-medium">Guests Services</div></a>
          <div class="card-content flex items-center h-full text-gray-500">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Placeat aut molestiae itaque ducimus eos amet quas vero perferendis praesentium, saepe doloribus maiores, repellendus soluta? Nulla qui quibusdam porro, nihil aut modi architecto?</div>
        </div>
        <div class="third-card w-1/4 flex flex-col border rounded-3xl border-gray-600 gap-2.5 p-5">
          <a href="{% url 'rooms:home' %}"><div class="card-head flex justify-center h-15 items-center border-white border-2 rounded-3xl bg-white text-black hover:bg-gray-200 duration-300 font-medium">Our Rooms</div></a>
          <div class="card-content flex items-center h-full text-gray-500">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Placeat aut molestiae itaque ducimus eos amet quas vero perferendis praesentium, saepe doloribus maiores, repellendus soluta? Nulla qui quibusdam porro, nihil aut modi architecto?</div>
        </div>
        <div class="fourth-card w-1/4 flex flex-col border rounded-3xl border-gray-600 gap-2.5 p-5">
          <a href="{% url 'services:home' %}"><div class="card-head flex justify-center h-15 items-center border-white border-2 rounded-3xl bg-white text-black hover:bg-gray-200 duration-300 font-medium">Our Services</div></a>
          <div class="card-content flex items-center h-full text-gray-500">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Placeat aut molestiae itaque ducimus eos amet quas vero perferendis praesentium, saepe doloribus maiores, repellendus soluta? Nulla qui quibusdam porro, nihil aut modi architecto?</div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}